---
title: "TP3_Bouzamondo"
author: "Mohamed Chadli Bouzamondo"
format: docx
editor: visual
---

## Annexe

```{r}
install.packages("crayon", repos = "http://cran.us.r-project.org")
library(crayon)
install.packages("quanteda", repos = "http://cran.us.r-project.org")
library(quanteda)
library(SnowballC)
library(tidyverse)
```

```{r}
## Insertion des bases de données

Fin_2008_1 <- read.csv("/Users/15150135/Documents/Analyse Big Data/fas_1001/_tp/_tp3/lipad/2008/2008-12-1.csv")

Fin_2008_2 <- read.csv("/Users/15150135/Documents/Analyse Big Data/fas_1001/_tp/_tp3/lipad/2008/2008-12-2.csv")

Fin_2008_3 <- read.csv("/Users/15150135/Documents/Analyse Big Data/fas_1001/_tp/_tp3/lipad/2008/2008-12-3.csv")

Fin_2008_4 <- read.csv("/Users/15150135/Documents/Analyse Big Data/fas_1001/_tp/_tp3/lipad/2008/2008-12-4.csv")
```

```{r}
##Combinaison des bases de données de 2008

Fin_2008 <- bind_rows(Fin_2008_1, Fin_2008_2, Fin_2008_3, Fin_2008_4)
```

```{r}
## Insertion du dictionnaire en anglais

lexicoder_en <- dictionary(file = "/Users/15150135/Documents/Analyse Big Data/fas_1001/dictionnary/policy_agendas_english.lcd", format = "yoshikoder")
```

```{r}
## Nettoyage de la base de données

Fin_2008_CLEAN <- Fin_2008 |> 
  select(speechtext, speakerparty) |> 
  ## Nettoyage de base ##
  mutate(speechtext = tolower(speechtext)) |> 
  ## remove NA's ##
  na.omit()
```

```{r}
## Téléchargement du clessnverse

run_dictionary <- function(data, text, dictionary) {
  tictoc::tic()
  if ( is.data.frame(data) != "TRUE") {
    stop(crayon::yellow('the argument "data" needs to be a dataframe'))
  }
  data <- data %>% dplyr::mutate(text = {{text}})
  if ( is.character(data$text) != "TRUE") {
    stop(crayon::yellow('The variable "text" needs to be a character vector'))
  }
  corpus <- quanteda::tokens(data$text)
  if ( quanteda::is.dictionary(dictionary) != "TRUE") {
    stop(crayon::yellow('Your "dictionary" needs to be in a dictionary format\n For more information:" https://quanteda.io/reference/dictionary.html'))
  }
  dfm    <- quanteda::dfm(quanteda::tokens_lookup(corpus, dictionary, nested_scope = "dictionary"))
  message(crayon::green("100% expressions/words found"))
  dataFinal   <- quanteda::convert(dfm, to = "data.frame")
  tictoc::toc()
  return(dataFinal)
}
```

```{r}
run_dictionary(data = Fin_2008_CLEAN, 
                    text = speechtext, 
                    dictionary = lexicoder_en) |> 
bind_cols(Fin_2008_CLEAN) |> 
select(-c(doc_id,speechtext)) |> 
  # Pivote la base de données pour voir la proportion par speaker #
  pivot_longer(!speakerparty, names_to = "categorie", values_to="n") |> 
  ungroup() |> 
  group_by(speakerparty, categorie) |> 
  summarise(n=sum(n)) |> 
  mutate(prop = round(n/sum(n),4)*100,
         speakerparty = case_when(speakerparty == "Conservative"          ~ "Conservateur",
                                  speakerparty == "Bloc Québ"           ~ "Vert",
                                  speakerparty == "New Democratic Party"  ~ "NDP",
                                  speakerparty == "Liberal"               ~ "Libéral",
                                  T ~ as.character(speakerparty)),
         categorie = case_when(categorie == "macroeconomics" ~ "Économie",
                               T ~ as.character(categorie))) |> 
  na.omit() |> 
  # On garde seulement le thème "économique" #
  filter(categorie %in% c("Économie"),
         !speakerparty == "Independent") |> 
  ggplot(aes(x = speakerparty, y = prop, fill = speakerparty)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual("", values = c("#0088CE", "#002395", "#EA6D6A", "#FF5800")) +
  labs(x = "Enjeu économique\n",
       y = "\nProportion (%)",
       title = "Discussion de l'enjeu économique par les partis politiques canadiens, \nen Décembre 2008") +
  theme_bw() +
  ## theme() en fonction des dimensions dans Quarto ##
  theme(title = element_text(size = 10),
        plot.title = element_text(hjust = 0.5, face='bold'),
        legend.text = element_text(size = 10),
        axis.text = element_text(size = 10, color = "black"))

```
